### ISSUE TITLE
redis.exceptions.ResponseError: unknown command 'PFCOUNT'

### ISSUE THREAD

**Issue by mohit0749** [istresearch/scrapy-cluster#133]
getting this error when i run the following script.
`python kafka_monitor.py run`

```
Traceback (most recent call last):
  File "kafka_monitor.py", line 559, in <module>
    sys.exit(main())
  File "kafka_monitor.py", line 543, in main
    kafka_monitor.run()
  File "kafka_monitor.py", line 401, in run
    self._main_loop()
  File "kafka_monitor.py", line 260, in _main_loop
    self._dump_stats()
  File "kafka_monitor.py", line 376, in _dump_stats
    extras[final] = self.stats_dict['total'][key].value()
  File "/usr/local/lib/python2.7/dist-packages/scutils/stats_collector.py", line 517, in value
    return self.redis_conn.execute_command("PFCOUNT", self.final_key)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 573, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 582, in read_response
    raise response
redis.exceptions.ResponseError: unknown command 'PFCOUNT'

```

**Comment by madisonb** [comment]
According to the documentation, `PFCOUNT` has been avaiable in Redis since 2.8.9 (released April 2014). I would recommend running at least 3.0, but older versions without `PFCOUNT` may still work if you set the stats-based flags to `False`.

Kafka Monitor:
* STATS_TOTAL: False
* STATS_PLUGINS: False

Redis Monitor:
* STATS_TOTAL: False
* STATS_PLUGINS: False

Crawler:
* STATS_STATUS_CODES: False

This should disable stats collection on all the different components, thus remove the need to execute the redis command that is failing.

If this answers your question please close this ticket.

**Comment by mohit0749** [comment]
thnks
it solved my problem.
