### ISSUE TITLE
exceptions.KeyError: 'crawlid'

### ISSUE THREAD

**Issue by bipabo1l** [istresearch/scrapy-cluster#168]
In order to crawl more urls I use splash.
My scrapy-cluster-1.1/crawler/crawling/spiders/link_spider.py:
```
import scrapy

from scrapy.http import Request
from lxmlhtml import CustomLxmlLinkExtractor as LinkExtractor
from scrapy.conf import settings
from crawling.items import RawResponseItem
from redis_spider import RedisSpider
from scrapy_splash import SplashRequest



class LinkSpider(RedisSpider):
    '''
    A spider that walks all links from the requested URL. This is
    the entrypoint for generic crawling.
    '''
    name = "link"
    allowed_domains = ['172.20.214.71']
    start_urls = ['http://172.20.214.71/url_0']

    js_source = """
        window.alert = function(msg){ console.log(msg) };
        window.confirm = function(msg){ console.log(msg); return false };
        window.prompt = function(text,defaultText){ console.log(text+defaultText); return false };
        window.history.back = function(args){console.log(args)};
        window.history.forward = function(args){ console.log(args)};
        var eles = document.getElementsByTagName('*');
        for (x in eles){
            elm = eles[x];
            for (i in elm){
                if (i.match(/^on(\w+)$/)){
                    if (elm[i]){
                        try {
                        elm[i]()
                        } catch (err) {console.log(err)};
                    };
                };
            };
        };
        """

    def __init__(self, *args, **kwargs):
        super(LinkSpider, self).__init__(*args, **kwargs)

    def start_requests(self):
       for url in self.start_urls:
           yield SplashRequest(url,
                               endpoint="render.html",
                               args={
                                   'js_source': self.js_source,
                                   'wait': 2,
                                   'image': 0},
                               cache_args=['js_source'],
                               dont_filter=False)

    def parse(self, response):
        #self._logger.debug("response: '{}'".format(response))
        self._logger.debug("crawled url {}".format(response.request.url))
        self._increment_status_code_stat(response)
        cur_depth = 0
        if 'curdepth' in response.meta:
            cur_depth = response.meta['curdepth']

        # capture raw response
        item = RawResponseItem()
        # populated from response.meta
        item['appid'] = response.meta['appid']
        item['crawlid'] = response.meta['crawlid']
        item['attrs'] = response.meta['attrs']

        # populated from raw HTTP response
        item["url"] = response.request.url
        item["response_url"] = response.url
        item["status_code"] = response.status
        item["status_msg"] = "OK"
        item["response_headers"] = self.reconstruct_headers(response)
        item["request_headers"] = response.request.headers
        item["body"] = response.body
        item["links"] = []

        # determine whether to continue spidering
        if cur_depth >= response.meta['maxdepth']:
            self._logger.debug("Not spidering links in '{}' because" \
                " cur_depth={} >= maxdepth={}".format(
                                                      response.url,
                                                      cur_depth,
                                                      response.meta['maxdepth']))
        else:
            # we are spidering -- yield Request for each discovered link
            link_extractor = LinkExtractor(
                restrict_css="body", tags=('a', 'area', 'form', 'iframe'), attrs=('href', 'action', 'src'),
                allow_domains=response.meta['allowed_domains'],
                allow=response.meta['allow_regex'],
                deny=response.meta['deny_regex'],
                deny_extensions=response.meta['deny_extensions'])

            for link in link_extractor.extract_links(response):
                # link that was discovered
                item["links"].append({"url": link.url, "text": link.text, })
                req = Request(link.url, callback=self.parse)

                # pass along all known meta fields
                for key in response.meta.keys():
                    req.meta[key] = response.meta[key]

                req.meta['priority'] = response.meta['priority'] - 10
                req.meta['curdepth'] = response.meta['curdepth'] + 1

                if 'useragent' in response.meta and \
                        response.meta['useragent'] is not None:
                    req.headers['User-Agent'] = response.meta['useragent']

                self._logger.debug("Trying to follow link '{}'".format(req.url))
                yield req

            for link in link_extractor.extract_links(response):
                req = SplashRequest(link.url, dont_filter=False, args={'wait': 2.5, 'image': 0})
                for key in response.meta.keys():
                    req.meta[key] = response.meta[key]
                yield req
        # raw response has been processed, yield to item pipeline
        yield item
```
And when I run `scrapy run link_spider`,I found this exception:
`Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/scrapy/commands/runspider.py", line 89, in run
    self.crawler_process.start()
  File "/usr/lib/python2.7/site-packages/scrapy/crawler.py", line 251, in start
    reactor.run(installSignalHandlers=False)  # blocking call
  File "/usr/lib64/python2.7/site-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/usr/lib64/python2.7/site-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib64/python2.7/site-packages/twisted/internet/base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/lib/python2.7/site-packages/scrapy/utils/reactor.py", line 41, in __call__
    return self._func(*self._a, **self._kw)
  File "/usr/lib/python2.7/site-packages/scrapy/core/engine.py", line 119, in _next_request
    self.crawl(request, spider)
  File "/usr/lib/python2.7/site-packages/scrapy/core/engine.py", line 183, in crawl
    self.schedule(request, spider)
  File "/usr/lib/python2.7/site-packages/scrapy/core/engine.py", line 189, in schedule
    if not self.slot.scheduler.enqueue_request(request):
  File "/export/Data/scrapy-cluster-1.1/crawler/crawling/distributed_scheduler.py", line 361, in enqueue_request
    if not request.dont_filter and self.dupefilter.request_seen(request):
  File "/export/Data/scrapy-cluster-1.1/crawler/crawling/redis_dupefilter.py", line 24, in request_seen
    c_id = request.meta['crawlid']
exceptions.KeyError: 'crawlid'`

![image](https://user-images.githubusercontent.com/20816849/35257558-f7c72fa2-0034-11e8-9043-87946bfd6511.png)

Can you help me？

**Comment by madisonb** [comment]
It appears like you have an invalid `start_requests()` method, as it doesn't have any of the meta information scrapy cluster needs. You should use the crawl API to yield requests to scrapy cluster, otherwise your spiders are going to crawl lots of duplicate pages.

If you would like, the development branch `splash` has splash support, but is not officially supported by this project yet.

Given that this is a [custom setup/issue](https://readthedocs.org/projects/scrapy-cluster/builds/6614715/) I am going to close this ticket. Feel free to move over to Gitter chat if you need further help
