### ISSUE TITLE
online integration test error

### ISSUE THREAD

**Issue by rawiafray** [istresearch/scrapy-cluster#224]
I'm trying to run the online integration test , i get this error : 
test_feed (__main__.TestKafkaMonitor) ... 2019-07-17 17:14:45,413 [kafka-monitor] ERROR: Failed to connect to Redis in ActionHandler
ERROR
test_run (__main__.TestKafkaMonitor) ... 2019-07-17 17:14:45,536 [kafka-monitor] ERROR: Failed to connect to Redis in ActionHandler
ERROR

======================================================================
ERROR: test_feed (__main__.TestKafkaMonitor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/online.py", line 56, in setUp
    self.kafka_monitor._load_plugins()
  File "/home/databiz40/scrapy-cluster/kafka-monitor/kafka_monitor.py", line 79, in _load_plugins
    instance.setup(self.settings)
  File "/home/databiz40/scrapy-cluster/kafka-monitor/plugins/action_handler.py", line 28, in setup
    sys.exit(1)
SystemExit: 1

======================================================================
ERROR: test_run (__main__.TestKafkaMonitor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/online.py", line 56, in setUp
    self.kafka_monitor._load_plugins()
  File "/home/databiz40/scrapy-cluster/kafka-monitor/kafka_monitor.py", line 79, in _load_plugins
    instance.setup(self.settings)
  File "/home/databiz40/scrapy-cluster/kafka-monitor/plugins/action_handler.py", line 28, in setup
    sys.exit(1)
SystemExit: 1

----------------------------------------------------------------------
Ran 2 tests in 0.242s

FAILED (errors=2)

**Comment by madisonb** [comment]
I would double check you have your redis settings correct, and your redis instance cli is accessible if you try to connect to it.

**Comment by madisonb** [comment]
Closing due to inactivity.
