### ISSUE TITLE
1.1 Troubles

### ISSUE THREAD

**Issue by quasiben** [istresearch/scrapy-cluster#31]
Having a bit of trouble getting started.  Below I've included commands and their outputs (note: some outputs are truncated):

```
python kafka_monitor.py run
2015-12-06 19:59:00,030 [kafka-monitor] INFO: Kafka Monitor Stats Dump:
{
    "fail_21600": 0,
    "fail_3600": 0,
    "fail_43200": 0,
    "fail_604800": 0,
....
    "plugin_StatsHandler_lifetime": 0,
    "total_21600": 13,
    "total_3600": 13,
    "total_43200": 13,
    "total_604800": 13,
    "total_86400": 13,
    "total_900": 1,
    "total_lifetime": 13
}

python redis_monitor.py
....
    "total_604800": 6,
    "total_86400": 6,
    "total_900": 0,
    "total_lifetime": 6
}
2015-12-06 20:02:39,862 [redis-monitor] INFO: Crawler Stats Dump:
{
    "total_spider_count": 0
}


scrapy runspider crawling/spiders/link_spider.py
2015-12-06 19:56:46,817 [scrapy-cluster] INFO: Changed Public IP: None -> 52.91.192.73

(scrapy_dev)ubuntu@ip-172-31-7-147:~/scrapy-cluster/kafka-monitor$ python kafka_monitor.py feed '{"url": "http://dmoz.org", "appid":"testapp", "crawlid":"abc1234", "maxdepth":1}'
No override settings found
2015-12-06 19:58:44,573 [kafka-monitor] INFO: Feeding JSON into demo.incoming
{
    "url": "http://dmoz.org",
    "maxdepth": 1,
    "crawlid": "abc1234",
    "appid": "testapp"
}
2015-12-06 19:58:44,580 [kafka-monitor] INFO: Successly fed item to Kafka

python kafkadump.py dump -t demo.crawled_firehose


(scrapy_dev)ubuntu@ip-172-31-7-147:~/scrapy-cluster/kafka-monitor$ python kafkadump.py dump -t demo.outbound_firehose
No override settings found
2015-12-06 19:35:31,640 [kafkadump] INFO: Connected to localhost:9092
{u'server_time': 1449430706, u'crawlid': u'abc1234', u'total_pending': 0, u'total_domains': 0, u'spiderid': u'link', u'appid': u'testapp', u'domains': {}, u'uuid': u'someuuid'}
```

I haven't changed any of the default settings and I'm currently using the `dev` branch.  However, I don't think my setup is working.  I was expecting some updates in `dump -t demo.crawled_firehose`.  So while I think I've successfully feed a url to be crawled `scrapy` isn't doing the crawl ? Any ideas?

**Comment by madisonb** [comment]
Your commands appear to be correct at first glance and without knowing if you are using our vagrant vm or your own kafka/redis cluster setup.

I dont quite have the 'debugging' 1.1 guide documented yet, but you can triple check your setup by running the `./run_online_tests.sh` to see if your setup appears to be working (this assumes you have proper localsettings.py files). It runs 4 integration tests to ensure your example cluster is set up.

Otherwise, I would always recommend turning on the DEBUG log for all three major portions -
`kafka_monitor.py run -ll DEBUG` (or add line to localsettings.py in km)
`redis_monitor.py -ll DEBUG` (or add line to localsettings.py in rm)
(change your scrapy localsettings.py to `SC_LOG_LEVEL = 'DEBUG'` and/or change `SC_LOG_STDOUT` to False so you can see debug statements independent of Scrapy debug logs. (I think that is it I am not at my work computer). 
And rerun your `scrapy runspider` command.

Doing those should spit out some style of log as to why your cluster isnt working right, or what stage things are getting stuck at.

**Comment by quasiben** [comment]
I'm running on my own setup on ec2.  Perhaps I should test on the Vagrant VM.  The `./run_online_tests.sh` executes successfully though there is an odd bit at the end:

```
OK
/home/ubuntu/scrapy-cluster/crawler/crawling/spiders/link_spider.py:5: ScrapyDeprecationWarning: Module `scrapy.conf` is deprecated, use `crawler.settings` attribute instead
  from scrapy.conf import settings
test_crawler_process (__main__.TestLinkSpider) ... /opt/anaconda/envs/scrapy_dev/lib/python2.7/site-packages/scrapy/utils/deprecate.py:155: ScrapyDeprecationWarning: `scrapy.contrib.downloadermiddleware.retry.RetryMiddleware` class is deprecated, use `scrapy.downloadermiddlewares.retry.RetryMiddleware` instead
  ScrapyDeprecationWarning)
/opt/anaconda/envs/scrapy_dev/lib/python2.7/site-packages/scrapy/utils/deprecate.py:155: ScrapyDeprecationWarning: `scrapy.contrib.downloadermiddleware.cookies.CookiesMiddleware` class is deprecated, use `scrapy.downloadermiddlewares.cookies.CookiesMiddleware` instead
  ScrapyDeprecationWarning)
/home/ubuntu/scrapy-cluster/crawler/crawling/custom_cookies.py:1: ScrapyDeprecationWarning: Module `scrapy.contrib.downloadermiddleware.cookies` is deprecated, use `scrapy.downloadermiddlewares.cookies` instead
  from scrapy.contrib.downloadermiddleware.cookies import CookiesMiddleware
/opt/anaconda/envs/scrapy_dev/lib/python2.7/site-packages/scrapy/utils/deprecate.py:155: ScrapyDeprecationWarning: `scrapy.contrib.spidermiddleware.depth.DepthMiddleware` class is deprecated, use `scrapy.spidermiddlewares.depth.DepthMiddleware` instead
  ScrapyDeprecationWarning)
2015-12-06 20:42:09,616 [scrapy-cluster] INFO: Changed Public IP: None -> 52.91.192.73
2015-12-06 20:42:17,321 [scrapy-cluster] INFO: Scraped page
2015-12-06 20:42:17,358 [scrapy-cluster] INFO: Sent page to Kafka
ok

----------------------------------------------------------------------
Ran 1 test in 25.912s

OK
```

I don't have a `localsettings.py` defined any where -- I was a bit confused here actually.  Is that file different than `settings.py` ?

**Comment by madisonb** [comment]
The odd bit at the end is a Scrapy import warning, in my investigation when I first saw that it looks like there is some code in scrapy that doesnt do some imports properly when using the new internal API.

The `localsettings.py` file is meant to allow you to override settings for multiple different kinds of deployments without have to overwrite core `settings.py` code. ie the 'default' setting is stored in `settings.py`, but you can override it and maintain your personal settings in a separate `localsettings.py` file. This serves three purposes - 1) splitting your custom settings from the default ones we provide, 2) Ensuring that if you mess your personal settings all up, you still have the defaults to fall back on, and 3) if we update the settings file doing a git pull wont stomp over your own.

So if all four tests pass appear to pass, can you listen to the test topic it uses and `dump` the results? To me it seems like you can 1) talk to redis 2) talk to kafka and 3) curl webpages from the box, so you should be seeing data in your `demo.crawled_firehose` topic. 

Otherwise if you use the DEBUG log level across all three components you should see what is causing the issue.

**Comment by madisonb** [comment]
In the code it appears to be the topic `demo_test.crawled_firehose`. So listen to that topic and then cd into the `crawler` folder and do `python tests/tests_online.py -v` and see if you get something back.

**Comment by quasiben** [comment]
Having just a bit of Vagrant trouble (should be resolved shortly).  In the time being though I thought I report various debug things:

```
#scrapy debug
2015-12-06 22:44:56,690 [scrapy-cluster] DEBUG: Added new Throttled Queue link:dmoz.org:queue
2015-12-06 22:44:56,696 [scrapy-cluster] DEBUG: Found url to crawl http://dmoz.org
2015-12-06 22:45:38,252 [scrapy-cluster] DEBUG: Current public ip: 52.91.192.73
2015-12-06 22:45:38,252 [scrapy-cluster] DEBUG: Reporting self id

#kafka monitor run
2015-12-06 22:47:00,202 [kafka-monitor] DEBUG: Compiling total/fail dump stats
2015-12-06 22:47:00,209 [kafka-monitor] DEBUG: Compiling plugin dump stats
2015-12-06 22:47:00,221 [kafka-monitor] INFO: Kafka Monitor Stats Dump:
─

#demo.crawled_firehose
2015-12-06 22:43:05,318 [kafkadump] DEBUG: Logging to stdout
2015-12-06 22:43:05,318 [kafkadump] DEBUG: Connecting to 52.91.192.73:9092...
2015-12-06 22:43:05,321 [kafkadump] INFO: Connected to 52.91.192.73:9092
2015-12-06 22:43:05,321 [kafkadump] DEBUG: Running dump command
2015-12-06 22:43:05,322 [kafkadump] DEBUG: Ensuring topic demo.crawled_firehose exists
2015-12-06 22:43:05,322 [kafkadump] DEBUG: Getting Kafka consumer
2015-12-06 22:43:05,350 [kafkadump] DEBUG: Reading from the end

#outbound firehose
(scrapy_dev)ubuntu@ip-172-31-7-147:~/scrapy-cluster/kafka-monitor$ python kafkadump.py dump -t demo.outbound_firehose
No override settings found
2015-12-06 20:16:39,061 [kafkadump] INFO: Connected to 52.91.192.73:9092
{u'server_time': 1449433077, u'crawlid': u'bz1234', u'total_pending': 0, u'total_domains': 0, u'spiderid': u'link', u'appid': u'testapp', u'domains': {}, u'uuid': u'someuuid'}
{u'server_time': 1449433087, u'crawlid': u'bz1234', u'total_pending': 0, u'total_domains': 0, u'spiderid': u'link', u'appid': u'testapp', u'domains': {}, u'uuid': u'someuuid'}
```

**Comment by quasiben** [comment]
I also ran `python tests/tests_online.py -v` in the `crawler` directory and nothing pops up on `demo_test.crawled_firehose`.  Notice in the log below the line `Not spidering links in 'http://istresearch.com/' ....`  Is that a problem ?

Also, happy to pick this up tomorrow

```
015-12-06 22:49:34,832 [scrapy-cluster] DEBUG: Found url to crawl www.istresearch.com
2015-12-06 22:49:34,979 [scrapy-cluster] DEBUG: Crawlid: '01234567890abcdefghijklmn' Appid: 'testapp' added to queue
2015-12-06 22:49:45,872 [scrapy-cluster] DEBUG: Found url to crawl http://istresearch.com/
2015-12-06 22:49:47,545 [scrapy-cluster] DEBUG: crawled url http://istresearch.com/
2015-12-06 22:49:47,549 [scrapy-cluster] DEBUG: Incremented status_code '200' stats
2015-12-06 22:49:47,549 [scrapy-cluster] DEBUG: Not spidering links in 'http://istresearch.com/' because cur_depth=0 >= maxdepth=0
2015-12-06 22:49:47,550 [scrapy-cluster] DEBUG: Processing item in LoggingBeforePipeline
2015-12-06 22:49:47,550 [scrapy-cluster] INFO: Scraped page
2015-12-06 22:49:47,550 [scrapy-cluster] DEBUG: Processing item in KafkaPipeline
2015-12-06 22:49:47,562 [scrapy-cluster] DEBUG: Processing item in LoggingAfterPipeline
2015-12-06 22:49:47,563 [scrapy-cluster] INFO: Sent page to Kafka
```

**Comment by madisonb** [comment]
You should always see in your crawler logs "Scraped Page", and "Sent Page to Kafka", this means that the crawler got the page and sent it to the kafka topic. The 'not spidering links' is a link spider output because you did not instruct it to crawl the links it found on the page as well (thats ok).

Everything above to me shows things working. Are you leaving the kafkadump utility running while all of this is happening? If you run the dump util _after_ you crawl the page (sequentially from the same command line), it moves the pointer to the end of the topic and you will not see your new data. In a separate terminal, if you leave the dump tool continuously running, then issue a crawl, you should see it come across the wire. 

You can use the `--from-beginning` or `-b` flag on the dump utility to consume everything from the beginning of the topic, as your data may be there but you are not seeing it come across at the right time. Try it on either the `demo_test.crawled_firehose`, `demo.crawled_firehose`, or `demo.outbound_firehose` (this one we know has data in it) and think they should be there.

**Comment by quasiben** [comment]
Ah, that makes sense.

I was monitoring on `demo.crawled_firehose`.  

`demo_test.crawled_firehose` has a fair amount of html :)

`demo.outbound_firehose` has nearly nothing:
```
(scrapy_dev)ubuntu@ip-172-31-7-147:~/scrapy-cluster/kafka-monitor$ python kafkadump.py dump --from-beginning -t demo_test.outbound_firehose -ll DEBUG
No override settings found
2015-12-06 23:30:46,008 [kafkadump] DEBUG: Logging to stdout
2015-12-06 23:30:46,008 [kafkadump] DEBUG: Connecting to 52.91.192.73:9092...
2015-12-06 23:30:46,012 [kafkadump] INFO: Connected to 52.91.192.73:9092
2015-12-06 23:30:46,012 [kafkadump] DEBUG: Running dump command
2015-12-06 23:30:46,012 [kafkadump] DEBUG: Ensuring topic demo_test.outbound_firehose exists
2015-12-06 23:30:46,012 [kafkadump] DEBUG: Getting Kafka consumer
2015-12-06 23:30:46,027 [kafkadump] DEBUG: Seeking to beginning
2015-12-06 23:30:46,035 [kafkadump] DEBUG: Received message
{u'info-test': u'ABC123', u'appid': u'someapp'}
2015-12-06 23:30:46,035 [kafkadump] DEBUG: Received message
{u'info-test': u'ABC123', u'appid': u'someapp'}
```
You repeated: `demo.crawled_firehose` -- not sure what the 2nd one should be.  
So yeah, things are working. I should also say that I am very new to both `kafka` and `scrapy` and very much appreciate your help!  Would you mind letting me keep the issue open until I resolve the problem with my setup?  This would mean a non-scrapy-cluster test successfully executing.

Also, happy to make changes to docs as I go a long if that's appropriate at this time ?

**Comment by madisonb** [comment]
This month I am going to write a massive amount of documentation which should cover everything we have discussed here - there are a lot of things out of date and I am going to clean it all up when transitioning from 1.0 to 1.1. Again - you are working on SC 1.1 where all our documentation is for 1.0 :)

You will have three kafka topics to look at:
* `demo.crawled_firehose` (the main crawl result html topic used in production)
* `demo.outbound_firehose` (the main info/action topic for getting information about your crawl)
* `demo_test.crawled_firehose` (notice the _test, generated by the online integration test when it tests to see if it can crawl things)

**Comment by quasiben** [comment]
Thanks -- this is helpful.

I think I've also got a bug now.  I ran: `scrapy runspider crawling/spiders/link_spider.py --loglevel DEBUG` with the feed: 

```
(scrapy_dev)ubuntu@ip-172-31-7-147:~/scrapy-cluster/kafka-monitor$ python kafka_monitor.py feed '{"url": "http://istresearch.com", "appid":"testapp", "crawlid":"abc123456"}'
No override settings found
2015-12-07 01:32:50,682 [kafka-monitor] INFO: Feeding JSON into demo.incoming
{
    "url": "http://istresearch.com",
    "crawlid": "abc123456",
    "appid": "testapp"
}
2015-12-07 01:32:50,690 [kafka-monitor] INFO: Successly fed item to Kafka
```

And got the following output
```
2015-12-07 01:32:54,795 [scrapy-cluster] DEBUG: Found url to crawl http://istresearch.com                                                                                                                                              [4/751]
2015-12-07 01:32:55 [scrapy] ERROR: Error downloading <GET http://istresearch.com>
Traceback (most recent call last):
  File "/opt/anaconda/envs/scrapy_dev/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/opt/anaconda/envs/scrapy_dev/lib/python2.7/site-packages/scrapy/resolver.py", line 26, in _cache_result
    dnscache[name] = result
  File "/opt/anaconda/envs/scrapy_dev/lib/python2.7/site-packages/scrapy/utils/datatypes.py", line 282, in __setitem__
    self.popitem(last=False)
  File "/opt/anaconda/envs/scrapy_dev/lib/python2.7/collections.py", line 164, in popitem
    raise KeyError('dictionary is empty')
KeyError: 'dictionary is empty'
```

**Comment by madisonb** [comment]
That looks like a Scrapy issue, I would try setting `DNSCACHE_ENABLED = True` in your crawler settings, we explicitly turn it off because the caching can mess things up for really long term spiders, but appears to be finicky for the OS the spiders run on. I would try that first.

**Comment by quasiben** [comment]
With `DNSCACHE_ENABLED = True` everything is now working.  Thanks!  Shall I close the issue ?

**Comment by madisonb** [comment]
Sure you can close this issue. As for the DNSCACHE it was originally raised in #15, and I have not seen it in our production boxes running centos but I have seen it on my macbook for local testing (which was why I suggested it). I will create a different issue or reopen the old one if it continually gives us problems. 

I can also triple check if our vagrant vm suffers this problem as well.

**Comment by quasiben** [comment]
Sounds good

**Comment by softwarevamp** [comment]
did you succeed with DNSCACHE_ENABLED = False? i still get KeyError: 'dictionary is empty'

**Comment by madisonb** [comment]
Given that `DNSCACHE_ENABLED` is a Scrapy setting, I would recommend trying to reproduce it within a normal scrapy project and submitting an issue on the Scrapy github project. If you cannot reproduce it with a normal scrapy project and suspect it is a scrapy cluster issue, please open a new ticket.

**Comment by softwarevamp** [comment]
there was a bug https://github.com/scrapy/scrapy/issues/2811 which has been fixed in scrapy.
