### ISSUE TITLE
Vagrant test environment missing cryptography method

### ISSUE THREAD

**Issue by anderfjord** [istresearch/scrapy-cluster#55]
Hi. I am in the process of spinning up the test environment, and have run into a few issues, some of which I was able to work around, but one which I've not been able to.

First, the successful workarounds:

- I had to manually change the Kafka and Zookeeper download urls in order to spin up the VM. The urls that were included were inaccessible.

- I had to manually install certain packages before being able to successfully install the project requirements.   (sudo apt-get install build-essential libssl-dev libffi-dev python-dev)

Unfortunately, now that I'm running the automated tests I keep getting an error about a certain crypto method not being present. Everything I'm finding online says the problem is due to a missing dependency on libssl-dev, but I already have that package installed, so I'm at a loss.

Here is the output I'm seeing at the end of running ./run_offline_tests.sh:

Traceback (most recent call last):
  File "tests/tests_offline.py", line 14, in <module>
    from crawling.redis_dupefilter import RFPDupeFilter
  File "/vagrant/crawler/crawling/redis_dupefilter.py", line 1, in <module>
    from scrapy.dupefilters import BaseDupeFilter
  File "/home/vagrant/.conda/envs/sc/lib/python2.7/site-packages/scrapy/__init__.py", line 48, in <module>
    from scrapy.spiders import Spider
  File "/home/vagrant/.conda/envs/sc/lib/python2.7/site-packages/scrapy/spiders/__init__.py", line 10, in <module>
    from scrapy.http import Request
  File "/home/vagrant/.conda/envs/sc/lib/python2.7/site-packages/scrapy/http/__init__.py", line 15, in <module>
    from scrapy.http.response.html import HtmlResponse
  File "/home/vagrant/.conda/envs/sc/lib/python2.7/site-packages/scrapy/http/response/html.py", line 8, in <module>
    from scrapy.http.response.text import TextResponse
  File "/home/vagrant/.conda/envs/sc/lib/python2.7/site-packages/scrapy/http/response/text.py", line 13, in <module>
    from scrapy.utils.response import get_base_url
  File "/home/vagrant/.conda/envs/sc/lib/python2.7/site-packages/scrapy/utils/response.py", line 12, in <module>
    from twisted.web import http
  File "/home/vagrant/.conda/envs/sc/lib/python2.7/site-packages/twisted/web/http.py", line 92, in <module>
    from twisted.internet import interfaces, reactor, protocol, address
  File "/home/vagrant/.conda/envs/sc/lib/python2.7/site-packages/twisted/internet/reactor.py", line 38, in <module>
    from twisted.internet import default
  File "/home/vagrant/.conda/envs/sc/lib/python2.7/site-packages/twisted/internet/default.py", line 56, in <module>
    install = _getInstallFunction(platform)
  File "/home/vagrant/.conda/envs/sc/lib/python2.7/site-packages/twisted/internet/default.py", line 44, in _getInstallFunction
    from twisted.internet.epollreactor import install
  File "/home/vagrant/.conda/envs/sc/lib/python2.7/site-packages/twisted/internet/epollreactor.py", line 24, in <module>
    from twisted.internet import posixbase
  File "/home/vagrant/.conda/envs/sc/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 18, in <module>
    from twisted.internet import error, udp, tcp
  File "/home/vagrant/.conda/envs/sc/lib/python2.7/site-packages/twisted/internet/tcp.py", line 29, in <module>
    from twisted.internet._newtls import (
  File "/home/vagrant/.conda/envs/sc/lib/python2.7/site-packages/twisted/internet/_newtls.py", line 21, in <module>
    from twisted.protocols.tls import TLSMemoryBIOFactory, TLSMemoryBIOProtocol
  File "/home/vagrant/.conda/envs/sc/lib/python2.7/site-packages/twisted/protocols/tls.py", line 41, in <module>
    from OpenSSL.SSL import Error, ZeroReturnError, WantReadError
  File "/home/vagrant/.conda/envs/sc/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/home/vagrant/.conda/envs/sc/lib/python2.7/site-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/home/vagrant/.conda/envs/sc/lib/python2.7/site-packages/OpenSSL/_util.py", line 7, in <module>
    binding = Binding()
  File "/home/vagrant/.conda/envs/sc/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 114, in __init__
    self._ensure_ffi_initialized()
  File "/home/vagrant/.conda/envs/sc/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 126, in _ensure_ffi_initialized
    cls._modules,
  File "/home/vagrant/.conda/envs/sc/lib/python2.7/site-packages/cryptography/hazmat/bindings/utils.py", line 31, in load_library_for_binding
    lib = ffi.verifier.load_library()
  File "/home/vagrant/.conda/envs/sc/lib/python2.7/site-packages/cffi/verifier.py", line 101, in load_library
    return self._load_library()
  File "/home/vagrant/.conda/envs/sc/lib/python2.7/site-packages/cffi/verifier.py", line 211, in _load_library
    return self._vengine.load_library()
  File "/home/vagrant/.conda/envs/sc/lib/python2.7/site-packages/cffi/vengine_cpy.py", line 155, in load_library
    raise ffiplatform.VerificationError(error)
cffi.ffiplatform.VerificationError: importing '/home/vagrant/.conda/envs/sc/lib/python2.7/site-packages/cryptography/_Cryptography_cffi_a269d620xd5c405b7.so': /home/vagrant/.conda/envs/sc/lib/python2.7/site-packages/cryptography/_Cryptography_cffi_a269d620xd5c405b7.so: undefined symbol: EC_GFp_nistp224_method

Any suggestions would be much appreciated. Thanks!

**Comment by madisonb** [comment]
@anderfjord Unfortunately sometimes apache changes the archive repos and it goes un noticed until someone like you tries to use them. I think the `dev` branch has the correct archive urls, would you mind destroying your VM and rebuilding from that branch? I just tried it and it worked. In the future this will be mitigated by #45 and then at some point #48.

As for your python package dependencies. The current VM is not set up to install Scrapy natively, you need to use the conda environment which is outlined [here](http://scrapy-cluster.readthedocs.org/en/latest/topics/introduction/quickstart.html) around step 7. 

I agree that the master branch should be updated to the newest urls so you can follow that documentation nicely.

**Comment by madisonb** [comment]
After further testing I have verified that both the `dev` and `master` branches are broken with the way we provision the quick start environment. I don't know what has happened to cause this but my guess is that conda has changed the way that they do things. 

While I continue testing, you have the core products scrapy cluster needs running at `scdev` (or use the IP address). You can use a virtualenv to install the pip requirements, or another linux flavored machine as long as your code can talk to the kafka and zookeeper hosts located at `scdev`.

**Comment by anderfjord** [comment]
Okay, I will revisit it soon. Thanks very much for the prompt and detailed response.

**Comment by madisonb** [comment]
I am going to close this soon as the PR above fixes this and demonstrates the whole stack in the virtual machine.

**Comment by anderfjord** [comment]
Sounds good. Thanks.

**Comment by madisonb** [comment]
Both dev and master branches successfully run all unit and integration tests. Closing.

https://travis-ci.org/istresearch/scrapy-cluster/branches
