### ISSUE TITLE
crawlid KeyError when using the default spider with maxdepth>=1

### ISSUE THREAD

**Issue by arthurpham** [istresearch/scrapy-cluster#84]
Hi,

Thank you for the project, i think it's great.
I was trying to set up scrapy-cluster using docker cloud with this stack : https://gist.github.com/arthurpham/d0167f32b7c5c77879748b541159dc61

When i try to run the following sample with maxdepth:0,

```
python kafka_monitor.py feed '{"url": "https://news.ycombinator.c
om", "appid":"testapp", "crawlid":"1", "maxdepth":0}'
```

The crawler is scraping properly and i can see the results on the `demo.crawled_firehose`.

```
crawler-2 | 2016-10-25T16:46:55.993628674Z 2016-10-25 16:46:55,992 [sc-crawler] INFO: Scraped page
crawler-2 | 2016-10-25T16:46:55.997765201Z 2016-10-25 16:46:55,997 [sc-crawler] INFO: Sent page to Kafka
```

But when i run the same sample but with maxdepth:1,

```
python kafka_monitor.py feed '{"url": "https://news.ycombinator.c
om", "appid":"testapp", "crawlid":"1", "maxdepth":1}'
```

I get this error `exceptions.KeyError: 'crawlid'`

```
crawler-2 | 2016-10-25T16:46:31.739078727Z Exception RuntimeError: 'generator ignored GeneratorExit' in <generator object iter_errback at 0x7f20fd6bb3c0> ignored
crawler-2 | 2016-10-25T16:46:31.746502925Z Unhandled error in Deferred:
crawler-2 | 2016-10-25T16:46:31.747008201Z 
crawler-2 | 2016-10-25T16:46:31.747056968Z 
crawler-2 | 2016-10-25T16:46:31.747088120Z Traceback (most recent call last):
crawler-2 | 2016-10-25T16:46:31.747113083Z   File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1195, in run
crawler-2 | 2016-10-25T16:46:31.747138039Z     self.mainLoop()
crawler-2 | 2016-10-25T16:46:31.747162226Z   File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1204, in mainLoop
crawler-2 | 2016-10-25T16:46:31.747186025Z     self.runUntilCurrent()
crawler-2 | 2016-10-25T16:46:31.747208068Z   File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 825, in runUntilCurrent
crawler-2 | 2016-10-25T16:46:31.747234945Z     call.func(*call.args, **call.kw)
crawler-2 | 2016-10-25T16:46:31.747268409Z   File "/usr/local/lib/python2.7/site-packages/twisted/internet/task.py", line 671, in _tick
crawler-2 | 2016-10-25T16:46:31.747293839Z     taskObj._oneWorkUnit()
crawler-2 | 2016-10-25T16:46:31.747317688Z --- <exception caught here> ---
crawler-2 | 2016-10-25T16:46:31.747342408Z   File "/usr/local/lib/python2.7/site-packages/twisted/internet/task.py", line 517, in _oneWorkUnit
crawler-2 | 2016-10-25T16:46:31.747367260Z     result = next(self._iterator)
crawler-2 | 2016-10-25T16:46:31.747388349Z   File "/usr/local/lib/python2.7/site-packages/scrapy/utils/defer.py", line 63, in <genexpr>
crawler-2 | 2016-10-25T16:46:31.747405893Z     work = (callable(elem, *args, **named) for elem in iterable)
crawler-2 | 2016-10-25T16:46:31.747427441Z   File "/usr/local/lib/python2.7/site-packages/scrapy/core/scraper.py", line 183, in _process_spidermw_output
crawler-2 | 2016-10-25T16:46:31.747452229Z     self.crawler.engine.crawl(request=output, spider=spider)
crawler-2 | 2016-10-25T16:46:31.749025377Z   File "/usr/local/lib/python2.7/site-packages/scrapy/core/engine.py", line 209, in crawl
crawler-2 | 2016-10-25T16:46:31.749049706Z     self.schedule(request, spider)
crawler-2 | 2016-10-25T16:46:31.749061377Z   File "/usr/local/lib/python2.7/site-packages/scrapy/core/engine.py", line 215, in schedule
crawler-2 | 2016-10-25T16:46:31.749072599Z     if not self.slot.scheduler.enqueue_request(request):
crawler-2 | 2016-10-25T16:46:31.749082999Z   File "/usr/src/app/crawling/distributed_scheduler.py", line 390, in enqueue_request
crawler-2 | 2016-10-25T16:46:31.749093973Z     if not request.dont_filter and self.dupefilter.request_seen(request):
crawler-2 | 2016-10-25T16:46:31.749104700Z   File "/usr/src/app/crawling/redis_dupefilter.py", line 24, in request_seen
crawler-2 | 2016-10-25T16:46:31.749115388Z     c_id = request.meta['crawlid']
crawler-2 | 2016-10-25T16:46:31.749125642Z exceptions.KeyError: 'crawlid'
```

Any idea on what i'm doing wrong ?

**Comment by madisonb** [comment]
Can you make sure you pulled the latest container image? This was an issue I had seen when others wanted to add their own custom spiders, so I added PR #80 to support automatic adding of the meta fields, which is what your issue appears to be. The request from the spider should have [this](https://github.com/istresearch/scrapy-cluster/blob/dev/crawler/crawling/settings.py#L142) new middleware that takes care of that.

Let me see if I can replicate it in the current containers and see what the issue is.

**Comment by arthurpham** [comment]
Thank you for the quick answer.

Here is a screenshot of what i see in the crawler container crawling/settings.py : http://screencast.com/t/aBQ14VGYzDOr

I should have the latest container image that are on docker hub. 
I'm using the crawler-dev-alpine, kafka-monitor-dev-alpine, redis-monitor-dev-alpine images. 

I saw the other PR #80 and #78 which is why i tested with different settings of maxdepth.

**Comment by madisonb** [comment]
If you turn on the scrapy logger you can see the issue
```
crawler_1        | 2016-10-25 21:06:25 [scrapy] INFO: Enabled spider middlewares:
crawler_1        | ['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
crawler_1        |  'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
crawler_1        |  'scrapy.spidermiddlewares.referer.RefererMiddleware',
crawler_1        |  'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware']
```
It appears like the middlewares are not being loaded.

**Comment by madisonb** [comment]
The only difference I see in the scrapy cluster spider middlewares is
```
    @classmethod
    def from_settings(cls, settings):
        return cls(settings)
```
instead of 
```
    @classmethod
    def from_crawler(cls, crawler):
        settings = crawler.settings
        return cls(settings)
```
Yet that doesnt seem to make a difference in whether scrapy loads the spider middleware.

**Comment by madisonb** [comment]
@arthurpham If you wait for the new containers to build from the commit referenced above, and try again, I successfully testing the `maxdepth` crawl and the middlewares were loaded properly. 

Sorry about that!

**Comment by arthurpham** [comment]
Yep, i redeployed the containers with your fix and that worked.
Thanks a lot !
